<?php

// Table fields name
	$in_counter = "#";
	$in_inter_name = "International name";
	$in_local_name = "Local name";
	$in_cd_count = "Number of CDs";
	$in_type = "Type";
	$in_comment = "Information";
	$in_user_fam_name = "Family Name";
	$in_user_name = "Surname";
	$in_user = "User";
	$in_pass = "Password";
	$in_new = "new";
	$in_old = "old";
	$in_as_above = "as above";


// Command buttons
	$in_edit_movie_button = "Edit movie";
	$in_edit_user_button = "Edit user";
	$in_delete_movie_button = "Delete movie";
	$in_delete_user_button = "Remove user";
	$in_confirm_button = "Confirm";

// Messages
	$in_edit_updated = "The changes have been saved";
	$in_user_edit_updated = "The user changes have been saved";
	$in_new_updated = "The movie has been inserted";
	$in_user_new_updated = "The user has been inserted";
	$in_delete_updated = "The movie has been deleted";
	$in_user_delete_updated = "The user has been removed";
	$in_unknown_movie = "Unknown movie";
	$in_unknown_user = "Unknown user";
	$in_pass_error = "Error while giving password!";
	$in_empty_field = "Empty field";
	$in_username_error = "Wrong username";
	$in_user_exists = "User exists";
	$in_no_authority = "The user is not authorized for this action.";

// Titles in various pages
	$in_home_page = "Home page";
	$in_all_movies = "Movie list";
	$in_all_users = "All users";
	$in_new_movie = "New movie";
	$in_new_user = "New user";
	$in_show_movie = "Display movie";
	$in_show_user = "User information";
	$in_edit_movie = "Edit movie";
	$in_edit_user = "Edit user";
	$in_options = "Options";
	$in_logout = "Logout";
	$in_deltitle_movie = "Delete movie";
	$in_deltitle_user = "Delete user";
	$in_authtitle = "Authenticate";
	
	$in_delete_movie = "Do you really want to delete this movie?";
	$in_delete_user = "Do you really want to remove this user?";
	$in_user_movies = "The user has the following movies";
	$in_select_user_movies = "Choose the movies this user has";
	$in_authenticate = "Please authenticate yourself";

	$in_opt_theme = "Available themes";
	$in_opt_lang = "Available languages";
	
	$in_welcome = "Welcome to <i>Our Movies <i>";
	$in_goodbye = "Thank you for using <i>Our Movies<i>\n<p/>Hope to see you soon!";


// Default config
	$def_codepage = "iso-8859-1";
	$def_title = "Our Movies";
?>
