<?php

// Table fields name
	$in_counter = "Α/Α";
	$in_inter_name = "Διεθνές Όνομα";
	$in_local_name = "Τοπικό Όνομα";
	$in_cd_count = "Αριθμός CDs";
	$in_type = "Μορφή";
	$in_comment = "Πληροφορίες";
	$in_user_fam_name = "Επώνυμο";
	$in_user_name = "Όνομα";
	$in_user = "Χρήστης";
	$in_pass = "Κωδικός";
	$in_new = "νέος";
	$in_old = "παλαιός";
	$in_as_above = "όπως προηγουμένως";


// Command buttons
	$in_edit_movie_button = "Διόρθωση ταινίας";
	$in_edit_user_button = "Διόρθωση στοιχείων";
	$in_delete_movie_button = "Διαγραφή ταινίας";
	$in_delete_user_button = "Διαγραφή χρήστη";
	$in_confirm_button = "Επικύρωση";

// Messages
	$in_edit_updated = "Οι αλλαγές στις ταινίες έγιναν";
	$in_user_edit_updated = "Οι αλλαγές στους χρήστες έγιναν";
	$in_new_updated = "Η ταινία εισήγθηκε";
	$in_user_new_updated = "Ο χρήστης εισήγθηκε";
	$in_delete_updated = "Η ταινία διαγράφθηκε";
	$in_user_delete_updated = "Ο χρήστης διαγράφθηκε";
	$in_unknown_movie = "¶γνωστη Ταινία";
	$in_unknown_user = "¶γνωστος χρήστης";
	$in_pass_error = "Λάθος στον κωδικό!";
	$in_empty_field = "Κενό στοιχείο";
	$in_username_error = "Αδύνατο όνομα χρήστη";
	$in_user_exists = "Ο χρήστης υπάρχει";
	$in_no_authority = "Ο χρήστης δεν έχει το δικαίωμα για αυτήν την πράξη";
	

// Titles in various pages
	$in_home_page = "Κεντρική Σελίδα";
	$in_all_movies = "Κατάλογος Ταινιών";
	$in_all_users = "Όλοι οι Χρήστες";
	$in_new_movie = "Νέα Ταινία";
	$in_new_user = "Νέος Χρήστης";
	$in_show_movie = "Εμφάνιση Ταινίας";
	$in_show_user = "Πληροφορίες Χρήστη";
	$in_edit_movie = "Επεξεργασία Ταινίας";
	$in_edit_user = "Επεξεργασία Χρήστη";
	$in_options = "Επιλογές";
	$in_logout = "Έξοδος";
	$in_deltitle_movie = "Διαγραφή Ταινίας";
	$in_deltitle_user = "Διαγραφή Χρήστη";
	$in_authtitle = "Είσοδος Κωδικού";

	$in_delete_movie = "Θέλετε πράγματι να διαγράψετε την επόμενη ταινία;";
	$in_delete_user = "Θέλετε πράγματι να διαγράψετε τον επόμενο χρήστη;";
	$in_user_movies = "Ο χρήστης έχει τις κάτωθι ταινίες";
	$in_select_user_movies = "Επιλέγξτε τις ταινίες που έχει ο συγκεκριμένος χρήστης";
	$in_authenticate = "Παρακαλώ εισάγετε το όνομά σας και τον κωδικό σας";


	$in_opt_theme = "Επιλογές Θέματος";
	$in_opt_lang = "Επιλογές γλώσσας";
	
	$in_welcome = "Καλωσήρθατε στις <i> ταινίες μας </i>";
	$in_goodbye = "Σας ευχαριστούμε που χρησιμοποιήσατε τις<i> ταινίες μας </i>\n<p/>Ελπίζουμε να σας ξαναδούμε σύντομα!";


// Default data
	$def_codepage = "iso-8859-7";
	$def_title = "Οι ταινίες μας";
?>
